### ISSUE TITLE
Unable to enter admin password with Enter

### ISSUE THREAD

**Issue by colfes** [spethso/Drinklist#47]
One is unable to enter the password of the admin panel with "Enter" and is forced to click the button instead.

**Comment by mee4895** [comment]
Fixed by https://github.com/spethso/Drinklist/commit/9ffd3e07a5c2e7c9f6c1267895546cca18d4f66a

**Comment by colfes** [comment]
Still unable to enter password with "Enter" using Mozilla Firefox (Windows 10).
Fix works w/ Chrome however.
